ALTER TABLE AMS_QUOTATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_QUOTATION CASCADE CONSTRAINTS;

CREATE TABLE AMS_QUOTATION
(
  QT_ID             VARCHAR2(8 BYTE),
  QT_RFQ_ID         VARCHAR2(8 BYTE),
  QT_ITEM_ID        VARCHAR2(8 BYTE),
  QT_ITEM_QTY       NUMBER(5),
  QT_RFQ_VENDOR_ID  VARCHAR2(8 BYTE),
  QT_DATE           DATE,
  QT_REF            VARCHAR2(10 BYTE),
  QT_DOD            DATE,
  QT_CURR_ID        VARCHAR2(5 BYTE),
  QT_UNIT_PRICE     NUMBER(8,2),
  QT_DISCOUNT       NUMBER(3),
  QT_MISE           VARCHAR2(10 BYTE),
  QT_TOTAL_AMT      NUMBER(8,2),
  QT_COMMENTS       VARCHAR2(40 BYTE),
  QT_STATUS         VARCHAR2(20 BYTE)
);


ALTER TABLE AMS_QUOTATION ADD (
  PRIMARY KEY
 (QT_ID));

