ALTER TABLE AMS_REQUEST_RELEASE_RESOURCE
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_REQUEST_RELEASE_RESOURCE CASCADE CONSTRAINTS;

CREATE TABLE AMS_REQUEST_RELEASE_RESOURCE
(
  REQID        VARCHAR2(100 BYTE),
  ASSET_ID     VARCHAR2(300 BYTE),
  DESCRIPTION  VARCHAR2(500 BYTE)
);


CREATE UNIQUE INDEX AMS_REQUEST_RELEASE_RESOURCEPK ON AMS_REQUEST_RELEASE_RESOURCE
(REQID);


ALTER TABLE AMS_REQUEST_RELEASE_RESOURCE ADD (
  CONSTRAINT AMS_REQUEST_RELEASE_RESOURCEPK
 PRIMARY KEY
 (REQID));

ALTER TABLE AMS_REQUEST_RELEASE_RESOURCE ADD (
  CONSTRAINT AMS_REQUEST_RELEASE_RESOUR_R03 
 FOREIGN KEY (REQID) 
 REFERENCES AMS_REQUEST (REQID)
    ON DELETE CASCADE);

