ALTER TABLE AMS_VENDOR
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_VENDOR CASCADE CONSTRAINTS;

CREATE TABLE AMS_VENDOR
(
  VENDOR_ID       VARCHAR2(8 BYTE),
  VENDOR_NAME     VARCHAR2(40 BYTE),
  VENDOR_EMAIL    VARCHAR2(40 BYTE),
  VENDOR_RATING   VARCHAR2(8 BYTE),
  VENDOR_STATUS   VARCHAR2(10 BYTE),
  VENDOR_ADDRESS  VARCHAR2(100 BYTE)
);


ALTER TABLE AMS_VENDOR ADD (
  PRIMARY KEY
 (VENDOR_ID));

