ALTER TABLE AMS_ROLE
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_ROLE CASCADE CONSTRAINTS;

CREATE TABLE AMS_ROLE
(
  ROLE_ID    VARCHAR2(8 BYTE),
  ROLE_NAME  VARCHAR2(40 BYTE)
);


ALTER TABLE AMS_ROLE ADD (
  PRIMARY KEY
 (ROLE_ID));

