DROP TABLE AMS_ASSET CASCADE CONSTRAINTS;

CREATE TABLE AMS_ASSET
(
  ASSET_ID               VARCHAR2(8 BYTE),
  ASSET_NAME             VARCHAR2(40 BYTE)      NOT NULL,
  ASSET_ASSET_TYPE_ID    VARCHAR2(8 BYTE)       NOT NULL,
  ASSET_VENDOR_ID        VARCHAR2(5 BYTE),
  ASSET_MAKE             VARCHAR2(10 BYTE),
  ASSET_TAG              VARCHAR2(10 BYTE),
  ASSET_CONFG            VARCHAR2(10 BYTE),
  ASSET_ALLOC_STATUS     VARCHAR2(10 BYTE),
  ASSET_WARRANTY_STATUS  VARCHAR2(10 BYTE),
  ASSET_REMARKS          VARCHAR2(40 BYTE),
  ASSET_VERSION          VARCHAR2(40 BYTE),
  ASSET_QUANTITY         NUMBER                 DEFAULT 1
);


CREATE UNIQUE INDEX AMS_ASSET_U01 ON AMS_ASSET
(ASSET_ID);


ALTER TABLE AMS_ASSET ADD (
  CONSTRAINT AMS_ASSET_U01
 UNIQUE (ASSET_ID));

