ALTER TABLE AMS_PO
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_PO CASCADE CONSTRAINTS;

CREATE TABLE AMS_PO
(
  PO_ID          VARCHAR2(8 BYTE),
  PO_RRF_ID      VARCHAR2(9 BYTE),
  PO_DATE        DATE,
  PO_STATUS      VARCHAR2(10 BYTE),
  PO_COMMENTS    VARCHAR2(40 BYTE),
  PO_SIGNATUTRE  BLOB
);


ALTER TABLE AMS_PO ADD (
  PRIMARY KEY
 (PO_ID));

ALTER TABLE AMS_PO ADD (
  FOREIGN KEY (PO_RRF_ID) 
 REFERENCES AMS_RRF (RRF_ID));

