ALTER TABLE EMAIL_TEMPLATE
 DROP PRIMARY KEY CASCADE;
DROP TABLE EMAIL_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE EMAIL_TEMPLATE
(
  TEMPLATENAME  VARCHAR2(20 BYTE),
  SENDTOQRY     VARCHAR2(100 BYTE),
  SENDTOQWHERE  VARCHAR2(100 BYTE),
  FROMTEXT      VARCHAR2(100 BYTE),
  SUBJECT       VARCHAR2(100 BYTE),
  BODYTEXT      VARCHAR2(400 BYTE)
);


ALTER TABLE EMAIL_TEMPLATE ADD (
  PRIMARY KEY
 (TEMPLATENAME));

