ALTER TABLE AMS_REQUEST_PCTRANSFER
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_REQUEST_PCTRANSFER CASCADE CONSTRAINTS;

CREATE TABLE AMS_REQUEST_PCTRANSFER
(
  REQID             VARCHAR2(100 BYTE),
  TRANSFER_TYPE     VARCHAR2(100 BYTE)          NOT NULL,
  USER1             VARCHAR2(100 BYTE),
  PCTRANSFER_USER1  VARCHAR2(300 BYTE),
  USER2             VARCHAR2(100 BYTE),
  PCTRANSFER_USER2  VARCHAR2(300 BYTE)
);


CREATE UNIQUE INDEX AMS_REQUEST_PCTRANSFER_PK ON AMS_REQUEST_PCTRANSFER
(REQID);


ALTER TABLE AMS_REQUEST_PCTRANSFER ADD (
  CONSTRAINT AMS_REQUEST_PCTRANSFER_PK
 PRIMARY KEY
 (REQID));

ALTER TABLE AMS_REQUEST_PCTRANSFER ADD (
  CONSTRAINT AMS_REQUEST_PCTRANSFER_R02 
 FOREIGN KEY (REQID) 
 REFERENCES AMS_REQUEST (REQID)
    ON DELETE CASCADE);

