ALTER TABLE PANEL_FIELDS
 DROP PRIMARY KEY CASCADE;
DROP TABLE PANEL_FIELDS CASCADE CONSTRAINTS;

CREATE TABLE PANEL_FIELDS
(
  SCR_NAME     VARCHAR2(20 CHAR),
  PANEL_NAME   VARCHAR2(20 CHAR),
  ORDERNO      VARCHAR2(20 CHAR),
  LBLNAME      VARCHAR2(40 CHAR),
  FNAME        VARCHAR2(40 CHAR),
  IDNAME       VARCHAR2(40 CHAR),
  DATATYPE     VARCHAR2(20 CHAR),
  DBCOL        VARCHAR2(25 BYTE),
  VALIDATION   VARCHAR2(255 CHAR),
  STRQUERY     VARCHAR2(255 CHAR),
  NROW         VARCHAR2(4 CHAR),
  NCOL         VARCHAR2(4 CHAR),
  CLASSNAME    VARCHAR2(20 CHAR),
  HTMLELM      VARCHAR2(30 CHAR),
  STORE_FLG    VARCHAR2(2 CHAR),
  PRKEY        VARCHAR2(20 CHAR),
  AUTOGEN      VARCHAR2(1 BYTE),
  ELEM_ATTRIB  VARCHAR2(100 BYTE)
);

COMMENT ON COLUMN PANEL_FIELDS.AUTOGEN IS 'Will get generated only while inserting';


CREATE UNIQUE INDEX PK_PANELFIELDS ON PANEL_FIELDS
(SCR_NAME, PANEL_NAME, ORDERNO);


ALTER TABLE PANEL_FIELDS ADD (
  CONSTRAINT PK_PANELFIELDS
 PRIMARY KEY
 (SCR_NAME, PANEL_NAME, ORDERNO));

