ALTER TABLE SCREEN
 DROP PRIMARY KEY CASCADE;
DROP TABLE SCREEN CASCADE CONSTRAINTS;

CREATE TABLE SCREEN
(
  SCR_NAME        VARCHAR2(20 CHAR),
  TEMPLATE_NAME   VARCHAR2(30 CHAR),
  JSNAME          VARCHAR2(100 CHAR),
  CSSNAME         VARCHAR2(100 CHAR),
  SPLWHERECLAUSE  VARCHAR2(255 CHAR),
  RELATEDPANEL    VARCHAR2(20 BYTE),
  BUSINESSLOGIC   VARCHAR2(100 BYTE),
  SCREEN_TITLE    VARCHAR2(30 BYTE)
);


CREATE UNIQUE INDEX PK_SCREEN ON SCREEN
(SCR_NAME);


ALTER TABLE SCREEN ADD (
  CONSTRAINT PK_SCREEN
 PRIMARY KEY
 (SCR_NAME));

