ALTER TABLE AMS_REQUEST_AMCRENEWAL
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_REQUEST_AMCRENEWAL CASCADE CONSTRAINTS;

CREATE TABLE AMS_REQUEST_AMCRENEWAL
(
  REQID          VARCHAR2(100 BYTE),
  ASSET_ID       VARCHAR2(300 BYTE),
  DELIVERY_NOTE  VARCHAR2(300 BYTE),
  DESCRIPTION    VARCHAR2(500 BYTE)
);


CREATE UNIQUE INDEX AMS_REQUEST_AMCRENEWAL_PK ON AMS_REQUEST_AMCRENEWAL
(REQID);


ALTER TABLE AMS_REQUEST_AMCRENEWAL ADD (
  CONSTRAINT AMS_REQUEST_AMCRENEWAL_PK
 PRIMARY KEY
 (REQID));

ALTER TABLE AMS_REQUEST_AMCRENEWAL ADD (
  CONSTRAINT AMS_REQUEST_AMCRENEWAL_R02 
 FOREIGN KEY (REQID) 
 REFERENCES AMS_REQUEST (REQID)
    ON DELETE CASCADE);

