ALTER TABLE AMS_EMPLOYEE
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE AMS_EMPLOYEE
(
  EMPID      VARCHAR2(25 BYTE)                  NOT NULL,
  EMPNAME    VARCHAR2(200 BYTE)                 NOT NULL,
  MGRID      VARCHAR2(25 BYTE),
  EMPEMAIL   VARCHAR2(100 BYTE),
  EMPDEPT    VARCHAR2(200 BYTE),
  ROLEID     VARCHAR2(8 BYTE),
  EMP_PH_NO  VARCHAR2(20 BYTE),
  PASSWORD   VARCHAR2(10 BYTE)
);


CREATE UNIQUE INDEX AMS_EMPLOYEE_PK ON AMS_EMPLOYEE
(EMPID);


ALTER TABLE AMS_EMPLOYEE ADD (
  CONSTRAINT AMS_EMPLOYEE_PK
 PRIMARY KEY
 (EMPID));

ALTER TABLE AMS_EMPLOYEE ADD (
  CONSTRAINT AMS_EMPLOYEE_ROLE_FK 
 FOREIGN KEY (ROLEID) 
 REFERENCES AMS_ROLE (ROLE_ID),
  CONSTRAINT AMS_EMPLOYEE_R01 
 FOREIGN KEY (MGRID) 
 REFERENCES AMS_EMPLOYEE (EMPID));

