ALTER TABLE AMS_ASSET_ALLOCATION
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_ASSET_ALLOCATION CASCADE CONSTRAINTS;

CREATE TABLE AMS_ASSET_ALLOCATION
(
  ASSET_ID          VARCHAR2(100 BYTE)          NOT NULL,
  ASSET_SNO         VARCHAR2(200 BYTE),
  ASSET_HOSTNAME    VARCHAR2(200 BYTE),
  ASSET_USERNAME    VARCHAR2(200 BYTE),
  ASSET_IP_ADDRESS  VARCHAR2(200 BYTE),
  ALLOC_ID          VARCHAR2(10 BYTE)
);


CREATE UNIQUE INDEX AMS_ASSET_ALLOCATION_PK ON AMS_ASSET_ALLOCATION
(ALLOC_ID);


ALTER TABLE AMS_ASSET_ALLOCATION ADD (
  CONSTRAINT AMS_ASSET_ALLOCATION_PK
 PRIMARY KEY
 (ALLOC_ID));

