ALTER TABLE AMS_DN
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_DN CASCADE CONSTRAINTS;

CREATE TABLE AMS_DN
(
  DN_ID               VARCHAR2(8 BYTE),
  DN_PO_ID            VARCHAR2(8 BYTE),
  DN_DOD              DATE,
  DN_DOR              DATE,
  DN_ORD_NO           VARCHAR2(8 BYTE)          NOT NULL,
  DN_WARRANTY_DATE    DATE,
  DN_INVOICE_NO       VARCHAR2(8 BYTE),
  DN_CHQ_NO           VARCHAR2(20 BYTE),
  DN_GOODS_CONDITION  CHAR(40 BYTE),
  DN_STATUS           CHAR(10 BYTE),
  DN_ITEM_ID          VARCHAR2(50 BYTE),
  DN_ITEM_QTY         VARCHAR2(25 BYTE),
  DN_ASSET_ID         VARCHAR2(8 BYTE)
);


ALTER TABLE AMS_DN ADD (
  PRIMARY KEY
 (DN_ID));

ALTER TABLE AMS_DN ADD (
  FOREIGN KEY (DN_PO_ID) 
 REFERENCES AMS_PO (PO_ID));

