SET DEFINE OFF;
Insert into AMS_DEPARTMENT
   (DEPT_ID, DEPT_NAME, DEPT_HEAD_ID, DEPT_VENDOR_ID, DEPT_STATUS)
 Values
   ('ISS', 'ISS', '2', '9891', 'Y');
Insert into AMS_DEPARTMENT
   (DEPT_ID, DEPT_NAME, DEPT_HEAD_ID, DEPT_VENDOR_ID, DEPT_STATUS)
 Values
   ('OAX', 'OAX', '3', '9121', 'Y');
COMMIT;
