SET DEFINE OFF;
Insert into AMS_REQUEST_TYPE
   (REQUESTTYPEID, REQUESTTYPE, REF_REQUESTTYPE, REF_TABLE)
 Values
   ('1', 'New Hardware', NULL, NULL);
Insert into AMS_REQUEST_TYPE
   (REQUESTTYPEID, REQUESTTYPE, REF_REQUESTTYPE, REF_TABLE)
 Values
   ('2', 'New Software', NULL, NULL);
Insert into AMS_REQUEST_TYPE
   (REQUESTTYPEID, REQUESTTYPE, REF_REQUESTTYPE, REF_TABLE)
 Values
   ('6', 'PC Transfer', NULL, NULL);
Insert into AMS_REQUEST_TYPE
   (REQUESTTYPEID, REQUESTTYPE, REF_REQUESTTYPE, REF_TABLE)
 Values
   ('7', 'Release Resource', NULL, NULL);
Insert into AMS_REQUEST_TYPE
   (REQUESTTYPEID, REQUESTTYPE, REF_REQUESTTYPE, REF_TABLE)
 Values
   ('5', 'AMC Renewal', NULL, NULL);
Insert into AMS_REQUEST_TYPE
   (REQUESTTYPEID, REQUESTTYPE, REF_REQUESTTYPE, REF_TABLE)
 Values
   ('3', 'Hardware Upgrade', NULL, NULL);
Insert into AMS_REQUEST_TYPE
   (REQUESTTYPEID, REQUESTTYPE, REF_REQUESTTYPE, REF_TABLE)
 Values
   ('4', 'Software Upgrade', NULL, NULL);
Insert into AMS_REQUEST_TYPE
   (REQUESTTYPEID, REQUESTTYPE, REF_REQUESTTYPE, REF_TABLE)
 Values
   ('8', 'Software Transfer', NULL, NULL);
COMMIT;
