SET DEFINE OFF;
Insert into AMS_ASSET
   (ASSET_ID, ASSET_NAME, ASSET_ASSET_TYPE_ID, ASSET_VENDOR_ID, ASSET_MAKE, 
    ASSET_TAG, ASSET_CONFG, ASSET_ALLOC_STATUS, ASSET_WARRANTY_STATUS, ASSET_REMARKS, 
    ASSET_VERSION, ASSET_QUANTITY)
 Values
   ('IT1', 'LAPTOP', 'HW', '9891', 'HP', 
    NULL, 'Pentium 4', 'FREE', 'ACTIVE', 'qqq', 
    NULL, 1);
Insert into AMS_ASSET
   (ASSET_ID, ASSET_NAME, ASSET_ASSET_TYPE_ID, ASSET_VENDOR_ID, ASSET_MAKE, 
    ASSET_TAG, ASSET_CONFG, ASSET_ALLOC_STATUS, ASSET_WARRANTY_STATUS, ASSET_REMARKS, 
    ASSET_VERSION, ASSET_QUANTITY)
 Values
   (NULL, 'KEYBOARD', 'HW', '9891', 'HP', 
    NULL, 'Standared', 'FREE', 'ACTIVE', NULL, 
    NULL, 1);
COMMIT;
