--Framework Related

@./SCREEN.sql;
@./SCREEN_PANEL.sql;
@./PANEL_FIELDS.sql;
@./USER_WFLID_APPID.sql;
@./AMS_MENU.sql;
@./WFLACTION_SCREEN_MAP.sql;
@./WFLNAME_ACTIVITY_MAP.sql;
@./WFLNAME_ACTIVITY_MAP.sql;

--Master Data
@./AMS_REQUEST_TYPE.sql;
@./AMS_ASSET_TYPE.sql;
@./AMS_DEPARTMENT.sql;
@./AMS_DEPT_VENDOR_MAP.sql;
@./AMS_EMPLOYEE.sql;
@./AMS_ROLE.sql;
@./AMS_VENDOR.sql;
@./AMS_CURRENCY.sql;

