SET DEFINE OFF;
Insert into AMS_ASSET_AVAILABILITY
   (ASSET_TYPE_ID, ASSET_NAME, ASSET_TOTAL, ASSET_AVAILABLE)
 Values
   ('SW', 'Windows XP', NULL, NULL);
Insert into AMS_ASSET_AVAILABILITY
   (ASSET_TYPE_ID, ASSET_NAME, ASSET_TOTAL, ASSET_AVAILABLE)
 Values
   ('SW', 'Oracle 9i', NULL, NULL);
COMMIT;
