SET DEFINE OFF;
Insert into AMS_ASSET_TYPE
   (ASSET_TYPE_ID, ASSET_TYPE_NAME, ASSET_TYPE_DEPT_ID, ASSET_TYPE_REF)
 Values
   ('HW', 'HARDWARE', '01', NULL);
Insert into AMS_ASSET_TYPE
   (ASSET_TYPE_ID, ASSET_TYPE_NAME, ASSET_TYPE_DEPT_ID, ASSET_TYPE_REF)
 Values
   ('SW', 'SOFTWARE', '01', NULL);
Insert into AMS_ASSET_TYPE
   (ASSET_TYPE_ID, ASSET_TYPE_NAME, ASSET_TYPE_DEPT_ID, ASSET_TYPE_REF)
 Values
   ('PC', 'Desktop PC', '01', 'HW');
Insert into AMS_ASSET_TYPE
   (ASSET_TYPE_ID, ASSET_TYPE_NAME, ASSET_TYPE_DEPT_ID, ASSET_TYPE_REF)
 Values
   ('LAP', 'Laptop', '01', 'HW');
Insert into AMS_ASSET_TYPE
   (ASSET_TYPE_ID, ASSET_TYPE_NAME, ASSET_TYPE_DEPT_ID, ASSET_TYPE_REF)
 Values
   ('RAM', 'RAM', '01', 'HW');
Insert into AMS_ASSET_TYPE
   (ASSET_TYPE_ID, ASSET_TYPE_NAME, ASSET_TYPE_DEPT_ID, ASSET_TYPE_REF)
 Values
   ('MON', 'Desktop Monitor', '01', 'HW');
COMMIT;
