ALTER TABLE AMS_MENU
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_MENU CASCADE CONSTRAINTS;

CREATE TABLE AMS_MENU
(
  MENU_ID       INTEGER,
  MENU_NAME     VARCHAR2(40 BYTE),
  MENU_ROLE_ID  VARCHAR2(10 BYTE),
  MENU_ACTION   VARCHAR2(100 BYTE)
);


ALTER TABLE AMS_MENU ADD (
  PRIMARY KEY
 (MENU_ID));

ALTER TABLE AMS_MENU ADD (
  CONSTRAINT AMS_MENU_R01 
 FOREIGN KEY (MENU_ROLE_ID) 
 REFERENCES AMS_ROLE (ROLE_ID));

