ALTER TABLE AMS_RFQ_VENDOR_MAP
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_RFQ_VENDOR_MAP CASCADE CONSTRAINTS;

CREATE TABLE AMS_RFQ_VENDOR_MAP
(
  RFQID             VARCHAR2(8 BYTE),
  VENDORID          VARCHAR2(8 BYTE),
  VENDORNAME        VARCHAR2(40 BYTE),
  TYPE_NOTIFY       VARCHAR2(10 BYTE),
  INDV_STATUS       VARCHAR2(12 BYTE),
  SUGGEST_DLV_TIME  NUMBER(4)
);


CREATE UNIQUE INDEX AMS_RFQ_VENDOR_MAP_PK ON AMS_RFQ_VENDOR_MAP
(RFQID, VENDORID);


ALTER TABLE AMS_RFQ_VENDOR_MAP ADD (
  CONSTRAINT AMS_RFQ_VENDOR_MAP_PK
 PRIMARY KEY
 (RFQID, VENDORID));

