ALTER TABLE AMS_REQUEST_SOFTWARE_TRANSFER
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_REQUEST_SOFTWARE_TRANSFER CASCADE CONSTRAINTS;

CREATE TABLE AMS_REQUEST_SOFTWARE_TRANSFER
(
  REQID       VARCHAR2(100 BYTE),
  ASSET_NAME  VARCHAR2(400 BYTE),
  USER_ID     VARCHAR2(100 BYTE),
  ASSET_ID    VARCHAR2(200 BYTE)
);


ALTER TABLE AMS_REQUEST_SOFTWARE_TRANSFER ADD (
  PRIMARY KEY
 (REQID));

ALTER TABLE AMS_REQUEST_SOFTWARE_TRANSFER ADD (
  CONSTRAINT AMS_REQUEST_SOFTWARE_TRANS_R04 
 FOREIGN KEY (REQID) 
 REFERENCES AMS_REQUEST (REQID)
    ON DELETE CASCADE);

