DROP TABLE USER_WFLID_APPID CASCADE CONSTRAINTS;

CREATE TABLE USER_WFLID_APPID
(
  USERID         VARCHAR2(40 BYTE),
  WFLID          VARCHAR2(20 BYTE),
  APPID          VARCHAR2(20 BYTE),
  STATUS         VARCHAR2(20 BYTE),
  WFLACTIONID    NUMBER(8),
  WFLACTIONDESC  VARCHAR2(20 BYTE)
);

COMMENT ON COLUMN USER_WFLID_APPID.WFLACTIONID IS 'Action id of workflow';

COMMENT ON COLUMN USER_WFLID_APPID.WFLACTIONDESC IS 'Action Desc';


create unique index IDX_USER_WFLID_APPID on USER_WFLID_APPID (APPID,WFLACTIONDESC) ;         

create  index IDX_USER_WFLID_APPID_APPID on USER_WFLID_APPID (APPID);