ALTER TABLE AMS_RRF
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_RRF CASCADE CONSTRAINTS;

CREATE TABLE AMS_RRF
(
  RRF_ID        VARCHAR2(8 BYTE),
  RRF_QT_ID     VARCHAR2(8 BYTE),
  RRF_REQ_ID    VARCHAR2(25 BYTE),
  RRF_DATE      DATE,
  RRF_STATUS    VARCHAR2(20 BYTE),
  RRF_APRV_ID   VARCHAR2(8 BYTE),
  RRF_COMMENTS  VARCHAR2(200 BYTE)
);


ALTER TABLE AMS_RRF ADD (
  PRIMARY KEY
 (RRF_ID));

