ALTER TABLE AMS_ASSET_AVAILABILITY
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_ASSET_AVAILABILITY CASCADE CONSTRAINTS;

CREATE TABLE AMS_ASSET_AVAILABILITY
(
  ASSET_TYPE_ID    VARCHAR2(40 BYTE),
  ASSET_NAME       VARCHAR2(300 BYTE),
  ASSET_TOTAL      INTEGER,
  ASSET_AVAILABLE  INTEGER
);


CREATE UNIQUE INDEX AMS_ASSET_AVAILABILITY_PK ON AMS_ASSET_AVAILABILITY
(ASSET_TYPE_ID, ASSET_NAME);


ALTER TABLE AMS_ASSET_AVAILABILITY ADD (
  CONSTRAINT AMS_ASSET_AVAILABILITY_PK
 PRIMARY KEY
 (ASSET_TYPE_ID, ASSET_NAME));

