ALTER TABLE AMS_REQUEST_TYPE
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_REQUEST_TYPE CASCADE CONSTRAINTS;

CREATE TABLE AMS_REQUEST_TYPE
(
  REQUESTTYPEID    VARCHAR2(29 BYTE)            NOT NULL,
  REQUESTTYPE      VARCHAR2(200 BYTE)           NOT NULL,
  REF_REQUESTTYPE  VARCHAR2(200 BYTE),
  REF_TABLE        VARCHAR2(50 BYTE)
);


CREATE UNIQUE INDEX AMS_REQUEST_TYPE_PK ON AMS_REQUEST_TYPE
(REQUESTTYPEID, REQUESTTYPE);


ALTER TABLE AMS_REQUEST_TYPE ADD (
  PRIMARY KEY
 (REQUESTTYPEID));

