ALTER TABLE AMS_RFQ
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_RFQ CASCADE CONSTRAINTS;

CREATE TABLE AMS_RFQ
(
  RFQ_ID         VARCHAR2(8 BYTE),
  RFQ_DEPT_ID    VARCHAR2(8 BYTE),
  RFQ_ITEM_ID    VARCHAR2(8 BYTE),
  RFQ_ITEM_QTY   NUMBER(5),
  RFQ_VENDOR_ID  VARCHAR2(8 BYTE),
  RFQ_STATUS     VARCHAR2(10 BYTE),
  RFQ_ITEM_TYPE  VARCHAR2(10 BYTE),
  RFQ_ITEM_DESC  VARCHAR2(200 BYTE)
);


ALTER TABLE AMS_RFQ ADD (
  PRIMARY KEY
 (RFQ_ID));

