DROP TABLE APPSTATUS CASCADE CONSTRAINTS;

CREATE TABLE APPSTATUS
(
  APPID     VARCHAR2(20 BYTE),
  ACTIVITY  VARCHAR2(8 BYTE),
  ACTION    VARCHAR2(8 BYTE),
  STATUS    VARCHAR2(2 BYTE)
);


