ALTER TABLE AMS_CURRENCY
 DROP PRIMARY KEY CASCADE;
DROP TABLE AMS_CURRENCY CASCADE CONSTRAINTS;

CREATE TABLE AMS_CURRENCY
(
  CURR_ID    VARCHAR2(3 BYTE),
  CURR_NAME  VARCHAR2(50 BYTE)
);


ALTER TABLE AMS_CURRENCY ADD (
  PRIMARY KEY
 (CURR_ID));

